FROM node:20

WORKDIR /app

# Kopieer vanuit de frontend map in de root naar de container
COPY frontend/package*.json ./

RUN npm install

# Kopieer de rest van de frontend code
COPY frontend/ .

EXPOSE 3000

# Start de dev-server in plaats van 'serve'
CMD ["npm", "run", "dev", "--", "--host", "--port", "3000"]