FROM python:3.11-slim

WORKDIR /app

# system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# copy requirements
COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# copy backend code
COPY backend /app

# expose FastAPI
EXPOSE 8000

# run server
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]